name: CI

on:
    pull_request:

    push:
        branches: [main]
        paths:
            - "domains/*"
            - "tests/*"
            - "util/*"
            - ".github/workflows/ci.yml"

    workflow_dispatch:

permissions:
    contents: read
    pull-requests: read

concurrency:
    group: ${{ github.ref }}-ci

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - run: npm install

            - name: Fetch PR information
              if: github.event_name == 'pull_request'
              env:
                  GH_TOKEN: ${{ github.token }}
                  PR_LOGIN: ${{ github.event.pull_request.user.login }}
                  PR_USER_ID: ${{ github.event.pull_request.user.id }}
                  PR_NUM: ${{ github.event.number }}
                  REPO: ${{ github.repository }}
              run: |
                  echo "PR_AUTHOR=$PR_LOGIN" >> $GITHUB_ENV
                  echo "PR_AUTHOR_ID=$PR_USER_ID" >> $GITHUB_ENV

                  LABELS=$(gh api --jq '[.labels[].name]' "/repos/$REPO/pulls/$PR_NUM")
                  echo "PR_LABELS=$LABELS" >> $GITHUB_ENV

                  FILES=$(gh api --jq '[.[] | select(.status != "removed") | .filename]' "/repos/$REPO/pulls/$PR_NUM/files")
                  echo "CHANGED_FILES=$FILES" >> $GITHUB_ENV

                  REMOVED_FILE_DATA=$(gh api --jq '[.[] | select(.status == "removed") | {name: .filename, data: .patch}]' "/repos/$REPO/pulls/$PR_NUM/files")
                  echo "DELETED_FILES=$REMOVED_FILE_DATA" >> $GITHUB_ENV

            - name: Run DNSControl tests
              if: github.event_name == 'pull_request' && contains(fromJson(env.CHANGED_FILES), 'dnsconfig.js')
              uses: is-a-dev/dnscontrol-action@main
              with:
                  args: check

            - name: Run tests
              run: npx ava tests/*.test.js --timeout=1m
